---

# Thanks to geerlingguy!

language: python
services: docker

env:
  global:
    - ROLE_NAME: terraform_project
  matrix:
    # Local user install
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: amazonlinux2
install:
  # Install test dependencies.
  - pip install -r molecule/requirements.txt

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-terraform-project xanmanning.$ROLE_NAME
  - cd xanmanning.$ROLE_NAME

script:
  # Run tests.
  - ansible-galaxy install xanmanning.terraform -p molecule/default/roles/
  - ansible-galaxy install xanmanning.terraform -p molecule/target/roles/
  - ansible-galaxy install xanmanning.terraform -p molecule/destroy/roles/
  - molecule check -s default
  - molecule test -s default
  - molecule check -s target
  - molecule test -s target
  - molecule check -s destroy
  - molecule test -s destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
