---

- name: Prepare containers for local-user install testing
  hosts: all
  become: true
  vars:
    terraform_install_dir: /usr/bin
    terraform_exec_projects:
      - project_path: /home/terraformuser/projects/null
        plan_file: null.tfplan
        state: planned
        force_init: true
  pre_tasks:
    - name: Ensure a user group exists
      group:
        name: user
        state: present

    - name: Ensure a normal user exists
      user:
        name: terraformuser
        group: user
        state: present

    - name: Ensure apt cache is updated
      apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'

    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present

    - name: Copy project directory
      copy:
        src: null/
        dest: /home/terraformuser/projects/null/
        owner: terraformuser
        group: user
        mode: 0755

  roles:
    - role: xanmanning.terraform

  tasks:
    - name: Ensure Terraform project is planned
      terraform:
        project_path: "{{ proj.project_path }}"
        state: planned
        plan_file: "{{ proj.plan_file | default('project.tfplan') }}"
        workspace: "{{ proj.workspace | default(omit) }}"
        lock: "{{ proj.lock | default(omit) }}"
        lock_timeout: "{{ proj.lock_timeout | default(omit) }}"
        force_init: "{{ proj.force_init | default(true) }}"
        backend_config: "{{ proj.backend_config | default(omit) }}"
        targets: "{{ proj.targets | default(omit) }}"
        variables_file: "{{ proj.variables_file | default(omit) }}"
        variables: "{{ proj.variables | default(omit) }}"
        binary_path: "{{ terraform_install_dir }}/terraform"
      loop: "{{ terraform_exec_projects }}"
      loop_control:
        loop_var: proj
