---

- import_tasks: pre_checks.yml

- include_tasks: terraform_run.yml
  loop: "{{ terraform_exec_projects }}"
  loop_control:
    loop_var: tfproj
  when:
    - terraform_exec_projects is defined
    - terraform_exec_projects is iterable
    - terraform_exec_projects | length >= 1
