---

- name: Ensure Terraform project is planned
  terraform:
    project_path: "{{ proj.project_path }}"
    binary_path: "{{ terraform_binary_path | default(omit) }}"
    state: planned
    plan_file: "{{ proj.plan_file | default('project.tfplan') }}"
    workspace: "{{ proj.workspace | default(omit) }}"
    lock: "{{ proj.lock | default(omit) }}"
    lock_timeout: "{{ proj.lock_timeout | default(omit) }}"
    force_init: "{{ proj.force_init | default(true) }}"
    backend_config: "{{ proj.backend_config | default(omit) }}"
    targets: "{{ proj.targets | default(omit) }}"
    variables_file: "{{ proj.variables_file | default(omit) }}"
    variables: "{{ proj.variables | default(omit) }}"
  check_mode: false
