---

- name: Display the Terraform Plan Summary
  debug:
    msg:
      - "+---------------------------------------------------------------+"
      - "|                    TERRAFORM PLAN SUMMARY                     |"
      - "+---------------------------------------------------------------+"
      - "  - {{ terraform_plan }}"
  when: ansible_check_mode

- name: Display the Terraform Execution Summary
  debug:
    var: terraform_exec_result.stdout_lines
  when: not ansible_check_mode

- name: Display the Terraform Output Summary
  debug:
    var: terraform_exec_result.outputs
  when: not ansible_check_mode
