---

- name: "Ensure Terraform project is {{ (proj.state | default('present')) if not terraform_destroy_all else 'absent' }}"
  terraform:
    project_path: "{{ proj.project_path }}"
    binary_path: "{{ terraform_binary_path | default(omit) }}"
    state: "{{ (proj.state | default('present')) if not terraform_destroy_all else 'absent' }}"
    plan_file: "{{ proj.plan_file | default('project.tfplan') }}"
    state_file: "{{ proj.state_file | default(omit) }}"
    workspace: "{{ proj.workspace | default(omit) }}"
    purge_workspace: "{{ proj.purge_workspace | default(false) }}"
    lock: "{{ proj.lock | default(omit) }}"
    lock_timeout: "{{ proj.lock_timeout | default(omit) }}"
    targets: "{{ proj.targets | default(omit) }}"
    variables_file: "{{ proj.variables_file | default(omit) }}"
    variables: "{{ proj.variables | default(omit) }}"
  register: terraform_exec_result

- name: Ensure outputs are written to JSON file
  copy:
    dest: "{{ proj.output_file | default(proj.project_path + '/outputs.json') }}"
    content: |
      {{ (terraform_exec_result.outputs | default({})) | to_nice_json(indent=2) }}
    mode: 0600
  when: terraform_exec_result.outputs is defined

- name: Ensure Terraform plan file is removed after run
  file:
    path: "{{ proj.plan_file | default('project.tfplan') }}"
    state: absent
