---

- name: Display the Terraform plan
  debug:
    msg:
      - "+---------------------------------------------------------------+"
      - "| {{ 'TERRAFORM PLAN'.center(61) }} |"
      - "+---------------------------------------------------------------+"
      - "{{ terraform_plan.split('\n') }}"

- name: Display the Terraform Plan Summary
  debug:
    msg:
      - "+---------------------------------------------------------------+"
      - "| {{ 'TERRAFORM PLAN SUMMARY'.center(61) }} |"
      - "+---------------------------------------------------------------+"
      - "| {{ terraform_plan_summary.center(61) }} |"
      - "+---------------------------------------------------------------+"
