---

name: CI
'on':
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 1 1 * *"

defaults:
  run:
    working-directory: "xanmanning.terraform_project"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian10
            scenario: default
          - distro: ubuntu2004
            scenario: default
          - distro: centos7
            scenario: destroy
          - distro: ubuntu1804
            scenario: destroy
          - distro: debian9
            scenario: target
          - distro: centos8
            scenario: target

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          path: "xanmanning.terraform_project"

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip3 install -r molecule/requirements.txt

      - name: Run Molecule check
        run: molecule check --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule test
        run: molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
